# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgot_pass.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui
from PySide2 import QtWidgets
import sys
import mysql.connector
from ok_popup import *
class Ui_Form(object):
    def change_pass(self):
        user = self.lineEdit.text()
        repass = self.lineEdit_4.text()
        dish = self.lineEdit_2.text()
        pas = self.lineEdit_3.text()
        mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        password="anirudh123",
        database="chitra_gupta"
        )
        mycursor = mydb.cursor()
        mycursor.execute("select * from login")
        data = mycursor.fetchall()
        data = [x[1] for x in data]

        if user not in data:
            msg = "No account exsits with the given user name"
            _translate = QCoreApplication.translate
            self.label_6.setText(_translate("Form", msg))
        else:
            mycursor.execute("select * from login where username = '{}'".format(user))
            data = mycursor.fetchall()
            if data[0][-1] != dish.lower():
                msg = "Answer to the security question is wrong."
                _translate = QCoreApplication.translate
                self.label_6.setText(_translate("Form", msg))
            elif repass != pas and len(pas)!=0:
                msg = "Both new passwords dont match."
                _translate = QCoreApplication.translate
                self.label_6.setText(_translate("Form", msg))
            else:
                mycursor.execute("update login set password = '{}' where idlogin = {}".format(pas,int(data[0][0])))
                mydb.commit()
                msg = "Password updated successfully."
                _translate = QCoreApplication.translate
                self.label_6.setText(_translate("Form", msg))
                


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(433, 341)
        self.verticalLayoutWidget = QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QRect(-1, -1, 441, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QSize(16777215, 30))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_3 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setEchoMode(QLineEdit.Password)
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_3 = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_2 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_4 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setEchoMode(QLineEdit.Password)
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_4 = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton = QPushButton(self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QSize(0, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.change_pass)
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_6 = QLabel(self.verticalLayoutWidget)
        font = QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Forgot Password"))
        self.label_2.setText(_translate("Form", "UserName"))
        self.label_5.setText(_translate("Form", "Re-enter New Password"))
        self.label_3.setText(_translate("Form", "   What is your favorite dish?"))
        self.label_4.setText(_translate("Form", "New Password"))
        self.pushButton.setText(_translate("Form", "Reset password"))
if __name__ == "__main__":
        app = QtWidgets.QApplication([])
        Form = QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())